import Head from "next/head";
import { useState } from "react";
import Image from "next/image";

export default function Home() {
  const [animalInput, setAnimalInput] = useState("");
  const [result, setResult] = useState();

  async function getNames(event) {
    event.preventDefault();
    const response = await fetch("/api/hello", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ animal: animalInput }),
    });
    const data = await response.json();
    setResult(data.result);
    setAnimalInput("");
  }


  return (
    <div className="h-screen flex items-start justify-center">
      <Head>
        <title>My Lovely Pet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dog.png" />
      </Head>

      <div className="mt-20 flex flex-col items-center">
        <div className="w-8">
          <Image src="/dog.png" alt="dog" height={60} width={70}/>
        </div>
        <div className="font-bold text-4xl mt-4 mb-8">Name my pet</div>
        <div className="w-80 mb-6">
          <input 
            className="w-80 py-3 px-4 rounded-md border-2 border-green-700"
            type="text"
            name="animal"
            placeholder="Enter an animal"
            value={animalInput}
            onChange={(e) => setAnimalInput(e.target.value)}
          />
        </div>
        <div className="py-3 rounded-md text-center text-white w-80 bg-green-700 mb-10" onClick={getNames}>Generate names</div>
        <div>{result}</div>
      </div>

    </div>
  )
}
